/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
              "outline": "#76777d",
              "tertiary": "#000000",
              "on-background": "#0b1c30",
              "outline-variant": "#c6c6cd",
              "tertiary-container": "#002113",
              "surface-container-high": "#dce9ff",
              "primary-fixed": "#dae2fd",
              "on-surface": "#0b1c30",
              "background": "#f8f9ff",
              "surface-container-low": "#eff4ff",
              "on-error-container": "#93000a",
              "on-tertiary": "#ffffff",
              "on-tertiary-fixed-variant": "#005236",
              "on-secondary-fixed-variant": "#005049",
              "surface-variant": "#d3e4fe",
              "inverse-on-surface": "#eaf1ff",
              "surface": "#f8f9ff",
              "primary": "#000000",
              "on-primary-container": "#7c839b",
              "on-primary-fixed": "#131b2e",
              "surface-dim": "#cbdbf5",
              "surface-container": "#e5eeff",
              "on-tertiary-container": "#009668",
              "surface-tint": "#565e74",
              "error": "#ba1a1a",
              "on-primary-fixed-variant": "#3f465c",
              "secondary": "#006a61",
              "on-secondary": "#ffffff",
              "secondary-container": "#86f2e4",
              "on-error": "#ffffff",
              "on-secondary-container": "#006f66",
              "surface-container-highest": "#d3e4fe",
              "surface-bright": "#f8f9ff",
              "secondary-fixed": "#89f5e7",
              "primary-container": "#131b2e",
              "on-tertiary-fixed": "#002113",
              "on-surface-variant": "#45464d",
              "secondary-fixed-dim": "#6bd8cb",
              "tertiary-fixed-dim": "#4edea3",
              "surface-container-lowest": "#ffffff",
              "on-secondary-fixed": "#00201d",
              "error-container": "#ffdad6",
              "tertiary-fixed": "#6ffbbe",
              "on-primary": "#ffffff",
      },
      "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
      },
      "spacing": {
              "gutter": "24px",
              "unit": "8px",
              "container-max-width": "1440px",
              "margin-mobile": "16px",
              "margin-desktop": "40px"
      },
      "fontFamily": {
              "label-sm": ["Inter"],
              "label-md": ["Inter"],
              "headline-md": ["Inter"],
              "headline-xl": ["Inter"],
              "headline-lg-mobile": ["Inter"],
              "body-sm": ["Inter"],
              "body-lg": ["Inter"],
              "code": ["jetbrainsMono"],
              "body-md": ["Inter"],
              "headline-lg": ["Inter"]
      },
      "fontSize": {
              "label-sm": ["12px", {"lineHeight": "16px", "fontWeight": "500"}],
              "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "600"}],
              "headline-md": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
              "headline-xl": ["36px", {"lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
              "headline-lg-mobile": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
              "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
              "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
              "code": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
              "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
              "headline-lg": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
}